# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_metadata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemetadata',
            old_name='json',
            new_name='content',
        ),
    ]
